@startuml
skinparam shadowing false
title Sequence - Tạo và nhận thông báo

participant "Nghiệp vụ hệ thống" as Domain
control "ThôngBáoService" as Service
entity "ThôngBáo" as Notify
control "Socket.IO" as Socket
control "Email SMTP" as Mail
database "MongoDB" as DB
actor "Người nhận" as User

Domain -> Service : tạo thông báo(loại, người nhận, liên kết)
Service -> Notify : insert
Notify -> DB : lưu thông báo
Service -> Socket : emit notification:new
Socket -> User : nhận realtime nếu online
opt Cần gửi email
  Service -> Mail : gửi email
  Mail -> User : email thông báo
end
@enduml

