@startuml
skinparam defaultFontName "Segoe UI"
skinparam defaultFontSize 13
skinparam shadowing false
skinparam linetype ortho
skinparam nodesep 50
skinparam ranksep 80
left to right direction
skinparam actorStyle stick
skinparam roundcorner 8
skinparam ArrowColor #333333
skinparam rectangleBorderColor #333333
skinparam boundary {
  BackgroundColor White
  BorderColor #333333
}
skinparam control {
  BackgroundColor White
  BorderColor #333333
}
skinparam entity {
  BackgroundColor White
  BorderColor #333333
}

actor "Khách vãng lai\n(from Usecase Diagram)" as Actor

together {
  boundary "dang-ky" as UI
  boundary "form-dang-ky" as Form
}

together {
  control "dang-ky-tai-khoan" as Controller
}

together {
  entity "NguoiDung" as NguoiDung
  entity "UngVien" as UngVien
  entity "NhaTuyenDung" as NhaTuyenDung
  entity "ThongBao" as ThongBao
}

Actor <--> UI
UI <--> Form
Form <--> Controller

Controller <--> NguoiDung
Controller <--> UngVien
Controller <--> NhaTuyenDung
Controller <--> ThongBao

NguoiDung -[hidden]right-> UngVien
UngVien -[hidden]right-> NhaTuyenDung
NhaTuyenDung -[hidden]right-> ThongBao
@enduml
