@startuml
skinparam defaultFontName "Segoe UI"
skinparam defaultFontSize 13
skinparam shadowing false
skinparam linetype ortho
skinparam nodesep 50
skinparam ranksep 80
left to right direction
skinparam actorStyle stick
skinparam roundcorner 8
skinparam ArrowColor #333333
skinparam rectangleBorderColor #333333
skinparam boundary {
  BackgroundColor White
  BorderColor #333333
}
skinparam control {
  BackgroundColor White
  BorderColor #333333
}
skinparam entity {
  BackgroundColor White
  BorderColor #333333
}

actor "Khách vãng lai\n(from Usecase Diagram)" as Actor

together {
  boundary "dang-nhap" as UI
  boundary "form-dang-nhap" as Form
  boundary "nut-dang-nhap-google" as GoogleBtn
}

together {
  control "dang-nhap" as Controller
  control "dang-nhap-google" as GoogleCtrl
}

together {
  entity "NguoiDung" as NguoiDung
  entity "UngVien" as UngVien
}

Actor <--> UI

UI <--> Form
UI <--> GoogleBtn
Form <--> Controller
GoogleBtn <--> GoogleCtrl

Controller <--> NguoiDung
Controller <--> UngVien
GoogleCtrl <--> NguoiDung
GoogleCtrl <--> UngVien
@enduml
