@startuml
skinparam defaultFontName "Segoe UI"
skinparam defaultFontSize 13
skinparam shadowing false
skinparam linetype ortho
left to right direction
skinparam actorStyle stick
skinparam roundcorner 8
skinparam ArrowColor #333333
skinparam rectangleBorderColor #333333
skinparam boundary {
  BackgroundColor White
  BorderColor #333333
}
skinparam control {
  BackgroundColor White
  BorderColor #333333
}
skinparam entity {
  BackgroundColor White
  BorderColor #333333
}

actor "Khách vãng lai\n(from Usecase Diagram)" as Actor
boundary "quen-mat-khau" as UI
boundary "form-quen-mat-khau" as Form
control "quen-mat-khau" as Controller

entity "NguoiDung" as MainEntity

Actor <--> UI
UI <--> Form
Form <--> Controller
Controller <--> MainEntity
@enduml
