@startuml
skinparam defaultFontName "Segoe UI"
skinparam defaultFontSize 13
skinparam shadowing false
skinparam linetype polyline
left to right direction
skinparam actorStyle stick
skinparam roundcorner 8
skinparam ArrowColor #333333
skinparam rectangleBorderColor #333333
skinparam boundary {
  BackgroundColor White
  BorderColor #333333
}
skinparam control {
  BackgroundColor White
  BorderColor #333333
}
skinparam entity {
  BackgroundColor White
  BorderColor #333333
}

actor "Khách vãng lai / Ứng viên\n(from Usecase Diagram)" as Actor
boundary "chi-tiet-viec-lam" as UI
boundary "khung-thao-tac-viec-lam" as Form
control "xem-chi-tiet-tin-tuyen-dung" as Controller

entity "TinTuyenDung" as MainEntity
entity "NhaTuyenDung" as E1
entity "DanhMucKyNang" as E2
entity "DanhGiaCongTy" as E3

Actor -right-> UI
UI -right-> Form
Form -right-> Controller

Controller -right-> MainEntity
Controller -right-> E1
Controller -right-> E2
Controller -right-> E3

MainEntity -down[hidden]-> E1
E1 -down[hidden]-> E2
E2 -down[hidden]-> E3
@enduml
