@startuml
skinparam defaultFontName "Segoe UI"
skinparam defaultFontSize 13
skinparam shadowing false
skinparam linetype ortho
skinparam nodesep 50
skinparam ranksep 80
left to right direction
skinparam actorStyle stick
skinparam roundcorner 8
skinparam ArrowColor #333333
skinparam rectangleBorderColor #333333
skinparam boundary {
  BackgroundColor White
  BorderColor #333333
}
skinparam control {
  BackgroundColor White
  BorderColor #333333
}
skinparam entity {
  BackgroundColor White
  BorderColor #333333
}

actor "Ứng viên\n(from Usecase Diagram)" as Actor

together {
  boundary "ho-so-nang-luc" as UI
  boundary "cv-studio" as Form
}

together {
  control "quan-ly-ho-so-nang-luc" as Controller
}

together {
  entity "HoSoNangLuc" as HoSoNangLuc
}

Actor <--> UI
UI <--> Form
Form <--> Controller
Controller <--> HoSoNangLuc
@enduml
