@startuml
skinparam defaultFontName "Segoe UI"
skinparam defaultFontSize 13
skinparam shadowing false
skinparam linetype ortho
skinparam nodesep 50
skinparam ranksep 80
top to bottom direction
skinparam actorStyle stick
skinparam roundcorner 8
skinparam ArrowColor #333333
skinparam rectangleBorderColor #333333
skinparam boundary {
  BackgroundColor White
  BorderColor #333333
}
skinparam control {
  BackgroundColor White
  BorderColor #333333
}
skinparam entity {
  BackgroundColor White
  BorderColor #333333
}

actor "Ứng viên\n(from Usecase Diagram)" as Actor

together {
  boundary "chi-tiet-viec-lam" as UI
  boundary "form-ung-tuyen" as Form
}

together {
  control "ung-tuyen-tin-tuyen-dung" as Controller
}

together {
  entity "HoSoUngTuyen" as HoSoUngTuyen
  entity "UngVien" as UngVien
  entity "TinTuyenDung" as TinTuyenDung
  entity "NhaTuyenDung" as NhaTuyenDung
  entity "HoSoNangLuc" as HoSoNangLuc
  entity "LichSuHoSoUngTuyen" as LichSuHoSoUngTuyen
  entity "ThongBao" as ThongBao
}

Actor <--> UI

UI <--> Form
Form <--> Controller

Controller <--> HoSoUngTuyen
Controller <--> UngVien
Controller <--> TinTuyenDung
Controller <--> NhaTuyenDung
Controller <--> HoSoNangLuc
Controller <--> LichSuHoSoUngTuyen
Controller <--> ThongBao
@enduml
