@startuml
skinparam defaultFontName "Segoe UI"
skinparam defaultFontSize 13
skinparam shadowing false
skinparam linetype polyline
left to right direction
skinparam actorStyle stick
skinparam roundcorner 8
skinparam ArrowColor #333333
skinparam rectangleBorderColor #333333
skinparam boundary {
  BackgroundColor White
  BorderColor #333333
}
skinparam control {
  BackgroundColor White
  BorderColor #333333
}
skinparam entity {
  BackgroundColor White
  BorderColor #333333
}

actor "Ứng viên\n(from Usecase Diagram)" as Actor
boundary "chi-tiet-viec-lam" as UI
boundary "form-ung-tuyen" as Form
control "ung-tuyen-tin-tuyen-dung" as Controller

entity "HoSoUngTuyen" as MainEntity
entity "UngVien" as E1
entity "TinTuyenDung" as E2
entity "HoSoNangLuc" as E3
entity "NhaTuyenDung" as E4
entity "ThongBao" as E5

Actor -right-> UI
UI -right-> Form
Form -right-> Controller

Controller -right-> MainEntity
Controller -right-> E1
Controller -right-> E2
Controller -right-> E3
Controller -right-> E4
Controller -right-> E5

MainEntity -down[hidden]-> E1
E1 -down[hidden]-> E2
E2 -down[hidden]-> E3
E3 -down[hidden]-> E4
E4 -down[hidden]-> E5
@enduml
