@startuml
skinparam defaultFontName "Segoe UI"
skinparam defaultFontSize 13
skinparam shadowing false
skinparam linetype ortho
left to right direction
skinparam actorStyle stick
skinparam roundcorner 8
skinparam ArrowColor #333333
skinparam rectangleBorderColor #333333
skinparam boundary {
  BackgroundColor White
  BorderColor #333333
}
skinparam control {
  BackgroundColor White
  BorderColor #333333
}
skinparam entity {
  BackgroundColor White
  BorderColor #333333
}

actor "Ứng viên\n(from Usecase Diagram)" as Actor
boundary "ho-so-ung-tuyen" as UI
boundary "bo-loc-trang-thai" as Form
control "theo-doi-trang-thai-ung-tuyen" as Controller

entity "HoSoUngTuyen" as MainEntity
entity "TinTuyenDung" as E1
entity "LichPhongVan" as E2

Actor <--> UI
UI <--> Form
Form <--> Controller
Controller <--> MainEntity
Controller <--> E1
Controller <--> E2
@enduml
