@startuml
skinparam defaultFontName "Segoe UI"
skinparam defaultFontSize 13
skinparam shadowing false
skinparam linetype ortho
left to right direction
skinparam actorStyle stick
skinparam roundcorner 8
skinparam ArrowColor #333333
skinparam rectangleBorderColor #333333
skinparam boundary {
  BackgroundColor White
  BorderColor #333333
}
skinparam control {
  BackgroundColor White
  BorderColor #333333
}
skinparam entity {
  BackgroundColor White
  BorderColor #333333
}

actor "Ứng viên\n(from Usecase Diagram)" as Actor
boundary "lich-phong-van" as UI
boundary "form-phan-hoi-lich" as Form
control "quan-ly-lich-phong-van" as Controller

entity "LichPhongVan" as MainEntity
entity "HoSoUngTuyen" as E1
entity "ThongBao" as E2

Actor <--> UI
UI <--> Form
Form <--> Controller
Controller <--> MainEntity
Controller <--> E1
Controller <--> E2
@enduml
