@startuml
skinparam defaultFontName "Segoe UI"
skinparam defaultFontSize 13
skinparam shadowing false
skinparam linetype ortho
skinparam nodesep 50
skinparam ranksep 80
left to right direction
skinparam actorStyle stick
skinparam roundcorner 8
skinparam ArrowColor #333333
skinparam rectangleBorderColor #333333
skinparam boundary {
  BackgroundColor White
  BorderColor #333333
}
skinparam control {
  BackgroundColor White
  BorderColor #333333
}
skinparam entity {
  BackgroundColor White
  BorderColor #333333
}

actor "Ứng viên\n(from Usecase Diagram)" as Actor

together {
  boundary "lich-phong-van" as UI
  boundary "chi-tiet-lich-phong-van" as Form
}

together {
  control "quan-ly-lich-phong-van" as Controller
}

together {
  entity "LichPhongVan" as LichPhongVan
  entity "HoSoUngTuyen" as HoSoUngTuyen
  entity "UngVien" as UngVien
  entity "ThongBao" as ThongBao
}

Actor <--> UI
UI <--> Form
Form <--> Controller

Controller <--> LichPhongVan
Controller <--> HoSoUngTuyen
Controller <--> UngVien
Controller <--> ThongBao

LichPhongVan -[hidden]right-> HoSoUngTuyen
HoSoUngTuyen -[hidden]right-> UngVien
UngVien -[hidden]right-> ThongBao
@enduml
