@startuml
skinparam defaultFontName "Segoe UI"
skinparam defaultFontSize 13
skinparam shadowing false
skinparam linetype ortho
skinparam nodesep 50
skinparam ranksep 80
top to bottom direction
skinparam actorStyle stick
skinparam roundcorner 8
skinparam ArrowColor #333333
skinparam rectangleBorderColor #333333
skinparam boundary {
  BackgroundColor White
  BorderColor #333333
}
skinparam control {
  BackgroundColor White
  BorderColor #333333
}
skinparam entity {
  BackgroundColor White
  BorderColor #333333
}

actor "Ứng viên\n(from Usecase Diagram)" as Actor

together {
  boundary "ho-so-ung-tuyen" as UI
  boundary "drawer-chi-tiet-ung-tuyen" as Form
}

together {
  control "danh-gia-cong-ty" as Controller
}

together {
  entity "DanhGiaCongTy" as DanhGiaCongTy
  entity "HoSoUngTuyen" as HoSoUngTuyen
  entity "LichPhongVan" as LichPhongVan
  entity "NhaTuyenDung" as NhaTuyenDung
  entity "UngVien" as UngVien
}

Actor <--> UI
UI <--> Form
Form <--> Controller

Controller <--> DanhGiaCongTy
Controller <--> HoSoUngTuyen
Controller <--> LichPhongVan
Controller <--> NhaTuyenDung
Controller <--> UngVien
@enduml
