@startuml
skinparam defaultFontName "Segoe UI"
skinparam defaultFontSize 13
skinparam shadowing false
skinparam linetype ortho
skinparam nodesep 50
skinparam ranksep 80
left to right direction
skinparam actorStyle stick
skinparam roundcorner 8
skinparam ArrowColor #333333
skinparam rectangleBorderColor #333333
skinparam boundary {
  BackgroundColor White
  BorderColor #333333
}
skinparam control {
  BackgroundColor White
  BorderColor #333333
}
skinparam entity {
  BackgroundColor White
  BorderColor #333333
}

actor "Nhà tuyển dụng\n(from Usecase Diagram)" as Actor

together {
  boundary "thong-tin-cong-ty" as UI
  boundary "form-ho-so-cong-ty" as Form
}

together {
  control "cap-nhat-ho-so-cong-ty" as Controller
}

together {
  entity "NhaTuyenDung" as NhaTuyenDung
  entity "ThongBao" as ThongBao
}

Actor <--> UI
UI <--> Form
Form <--> Controller

Controller <--> NhaTuyenDung
Controller <--> ThongBao

NhaTuyenDung -[hidden]right-> ThongBao
@enduml
