@startuml
skinparam defaultFontName "Segoe UI"
skinparam defaultFontSize 13
skinparam shadowing false
skinparam linetype ortho
skinparam nodesep 50
skinparam ranksep 80
top to bottom direction
skinparam actorStyle stick
skinparam roundcorner 8
skinparam ArrowColor #333333
skinparam rectangleBorderColor #333333
skinparam boundary {
  BackgroundColor White
  BorderColor #333333
}
skinparam control {
  BackgroundColor White
  BorderColor #333333
}
skinparam entity {
  BackgroundColor White
  BorderColor #333333
}

actor "Nhà tuyển dụng\n(from Usecase Diagram)" as Actor

together {
  boundary "quan-ly-tin" as UI
  boundary "form-dang-tin" as Form
}

together {
  control "dang-tin-tuyen-dung" as Controller
}

together {
  entity "TinTuyenDung" as TinTuyenDung
  entity "TinTuyenDungKyNang" as TinTuyenDungKyNang
  entity "DanhMucKyNang" as DanhMucKyNang
  entity "NhaTuyenDung" as NhaTuyenDung
  entity "ThongBao" as ThongBao
}

Actor <--> UI
UI <--> Form
Form <--> Controller

Controller <--> NhaTuyenDung
Controller <--> TinTuyenDung
Controller <--> TinTuyenDungKyNang
Controller <--> DanhMucKyNang
Controller <--> ThongBao
@enduml
