@startuml
skinparam defaultFontName "Segoe UI"
skinparam defaultFontSize 13
skinparam shadowing false
skinparam linetype ortho
skinparam nodesep 50
skinparam ranksep 80
left to right direction
skinparam actorStyle stick
skinparam roundcorner 8
skinparam ArrowColor #333333
skinparam rectangleBorderColor #333333
skinparam boundary {
  BackgroundColor White
  BorderColor #333333
}
skinparam control {
  BackgroundColor White
  BorderColor #333333
}
skinparam entity {
  BackgroundColor White
  BorderColor #333333
}

actor "Nhà tuyển dụng\n(from Usecase Diagram)" as Actor

together {
  boundary "quan-ly-tin" as UI
  boundary "form-sua-tin" as Form
}

together {
  control "quan-ly-tin-tuyen-dung" as Controller
}

together {
  entity "TinTuyenDung" as TinTuyenDung
  entity "TinTuyenDungKyNang" as TinTuyenDungKyNang
}

Actor <--> UI
UI <--> Form
Form <--> Controller

Controller <--> TinTuyenDung
Controller <--> TinTuyenDungKyNang

TinTuyenDung -[hidden]right-> TinTuyenDungKyNang
@enduml
