@startuml
skinparam defaultFontName "Segoe UI"
skinparam defaultFontSize 13
skinparam shadowing false
skinparam linetype ortho
skinparam nodesep 50
skinparam ranksep 80
top to bottom direction
skinparam actorStyle stick
skinparam roundcorner 8
skinparam ArrowColor #333333
skinparam rectangleBorderColor #333333
skinparam boundary {
  BackgroundColor White
  BorderColor #333333
}
skinparam control {
  BackgroundColor White
  BorderColor #333333
}
skinparam entity {
  BackgroundColor White
  BorderColor #333333
}

actor "Nhà tuyển dụng\n(from Usecase Diagram)" as Actor

together {
  boundary "pipeline-ung-vien" as UI
  boundary "drawer-ho-so-ung-vien" as Form
}

together {
  control "quan-ly-ho-so-ung-vien" as Controller
}

together {
  entity "HoSoUngTuyen" as HoSoUngTuyen
  entity "UngVien" as UngVien
  entity "TinTuyenDung" as TinTuyenDung
  entity "HoSoNangLuc" as HoSoNangLuc
  entity "LichSuHoSoUngTuyen" as LichSuHoSoUngTuyen
  entity "ThongBao" as ThongBao
}

Actor <--> UI
UI <--> Form
Form <--> Controller

Controller <--> HoSoUngTuyen
Controller <--> UngVien
Controller <--> TinTuyenDung
Controller <--> HoSoNangLuc
Controller <--> LichSuHoSoUngTuyen
Controller <--> ThongBao
@enduml
