@startuml
skinparam defaultFontName "Segoe UI"
skinparam defaultFontSize 13
skinparam shadowing false
skinparam linetype polyline
left to right direction
skinparam actorStyle stick
skinparam roundcorner 8
skinparam ArrowColor #333333
skinparam rectangleBorderColor #333333
skinparam boundary {
  BackgroundColor White
  BorderColor #333333
}
skinparam control {
  BackgroundColor White
  BorderColor #333333
}
skinparam entity {
  BackgroundColor White
  BorderColor #333333
}

actor "Nhà tuyển dụng\n(from Usecase Diagram)" as Actor
boundary "lich-phong-van-ntd" as UI
boundary "form-ket-qua-phong-van" as Form
control "cap-nhat-ket-qua-phong-van" as Controller

entity "LichPhongVan" as MainEntity
entity "HoSoUngTuyen" as E1
entity "UngVien" as E2
entity "TinTuyenDung" as E3
entity "ThongBao" as E4

Actor -right-> UI
UI -right-> Form
Form -right-> Controller

Controller -right-> MainEntity
Controller -right-> E1
Controller -right-> E2
Controller -right-> E3
Controller -right-> E4

MainEntity -down[hidden]-> E1
E1 -down[hidden]-> E2
E2 -down[hidden]-> E3
E3 -down[hidden]-> E4
@enduml
