@startuml
skinparam defaultFontName "Segoe UI"
skinparam defaultFontSize 13
skinparam shadowing false
skinparam linetype ortho
left to right direction
skinparam actorStyle stick
skinparam roundcorner 8
skinparam ArrowColor #333333
skinparam rectangleBorderColor #333333
skinparam boundary {
  BackgroundColor White
  BorderColor #333333
}
skinparam control {
  BackgroundColor White
  BorderColor #333333
}
skinparam entity {
  BackgroundColor White
  BorderColor #333333
}

actor "Quản trị viên\n(from Usecase Diagram)" as Actor
boundary "quan-tri-nguoi-dung" as UI
boundary "form-tai-khoan" as Form
control "quan-ly-nguoi-dung" as Controller

entity "NguoiDung" as MainEntity
entity "UngVien" as E1
entity "NhaTuyenDung" as E2

Actor <--> UI
UI <--> Form
Form <--> Controller
Controller <--> MainEntity
Controller <--> E1
Controller <--> E2
@enduml
