@startuml
skinparam defaultFontName "Segoe UI"
skinparam defaultFontSize 13
skinparam shadowing false
skinparam linetype ortho
left to right direction
skinparam actorStyle stick
skinparam roundcorner 8
skinparam ArrowColor #333333
skinparam rectangleBorderColor #333333
skinparam boundary {
  BackgroundColor White
  BorderColor #333333
}
skinparam control {
  BackgroundColor White
  BorderColor #333333
}
skinparam entity {
  BackgroundColor White
  BorderColor #333333
}

actor "Quản trị viên\n(from Usecase Diagram)" as Actor
boundary "quan-tri-tin-tuyen-dung" as UI
boundary "form-duyet-tin" as Form
control "duyet-tin-tuyen-dung" as Controller

entity "TinTuyenDung" as MainEntity
entity "NhaTuyenDung" as E1
entity "ThongBao" as E2

Actor <--> UI
UI <--> Form
Form <--> Controller
Controller <--> MainEntity
Controller <--> E1
Controller <--> E2
entity "TinTuyenDungKyNang" as TinTuyenDungKyNang
Controller -right-> TinTuyenDungKyNang
@enduml
