@startuml
skinparam defaultFontName "Segoe UI"
skinparam defaultFontSize 13
skinparam shadowing false
skinparam linetype polyline
left to right direction
skinparam actorStyle stick
skinparam roundcorner 8
skinparam ArrowColor #333333
skinparam rectangleBorderColor #333333
skinparam boundary {
  BackgroundColor White
  BorderColor #333333
}
skinparam control {
  BackgroundColor White
  BorderColor #333333
}
skinparam entity {
  BackgroundColor White
  BorderColor #333333
}

actor "Quản trị viên\n(from Usecase Diagram)" as Actor
boundary "quan-tri-review" as UI
boundary "form-duyet-review" as Form
control "duyet-danh-gia-cong-ty" as Controller

entity "DanhGiaCongTy" as MainEntity
entity "UngVien" as E1
entity "NhaTuyenDung" as E2
entity "HoSoUngTuyen" as E3

Actor -right-> UI
UI -right-> Form
Form -right-> Controller

Controller -right-> MainEntity
Controller -right-> E1
Controller -right-> E2
Controller -right-> E3

MainEntity -down[hidden]-> E1
E1 -down[hidden]-> E2
E2 -down[hidden]-> E3
@enduml
