@startuml
skinparam defaultFontName "Segoe UI"
skinparam defaultFontSize 13
skinparam shadowing false
skinparam linetype ortho
skinparam nodesep 50
skinparam ranksep 80
left to right direction
skinparam actorStyle stick
skinparam roundcorner 8
skinparam ArrowColor #333333
skinparam rectangleBorderColor #333333
skinparam boundary {
  BackgroundColor White
  BorderColor #333333
}
skinparam control {
  BackgroundColor White
  BorderColor #333333
}
skinparam entity {
  BackgroundColor White
  BorderColor #333333
}

actor "Quản trị viên\n(from Usecase Diagram)" as Actor

together {
  boundary "quan-tri-review" as UI
  boundary "form-duyet-review" as Form
}

together {
  control "duyet-danh-gia-cong-ty" as Controller
}

together {
  entity "DanhGiaCongTy" as DanhGiaCongTy
}

Actor <--> UI
UI <--> Form
Form <--> Controller
Controller <--> DanhGiaCongTy
@enduml
