@startuml
skinparam defaultFontName "Segoe UI"
skinparam defaultFontSize 13
skinparam shadowing false
skinparam linetype polyline
left to right direction
skinparam actorStyle stick
skinparam roundcorner 8
skinparam ArrowColor #333333
skinparam rectangleBorderColor #333333
skinparam boundary {
  BackgroundColor White
  BorderColor #333333
}
skinparam control {
  BackgroundColor White
  BorderColor #333333
}
skinparam entity {
  BackgroundColor White
  BorderColor #333333
}

actor "Quản trị viên\n(from Usecase Diagram)" as Actor
boundary "quan-tri-dashboard" as UI
boundary "bo-loc-thong-ke" as Form
control "xem-thong-ke-he-thong" as Controller

entity "NguoiDung" as MainEntity
entity "NhaTuyenDung" as E1
entity "TinTuyenDung" as E2
entity "HoSoUngTuyen" as E3

Actor -right-> UI
UI -right-> Form
Form -right-> Controller

Controller -right-> MainEntity
Controller -right-> E1
Controller -right-> E2
Controller -right-> E3

MainEntity -down[hidden]-> E1
E1 -down[hidden]-> E2
E2 -down[hidden]-> E3
entity "LichSuHoSoUngTuyen" as LichSuHoSoUngTuyen
entity "TinTuyenDungKyNang" as TinTuyenDungKyNang
entity "DanhGiaPhongVan" as DanhGiaPhongVan
Controller -right-> LichSuHoSoUngTuyen
Controller -right-> TinTuyenDungKyNang
Controller -right-> DanhGiaPhongVan
@enduml
